
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.62.91:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: docker-mysql123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
